2.1 Data Manipulation


In [1]:
import numpy as np
import torch

In [2]:
x=torch.arange(12,dtype=int)

In [3]:
x.numel()

12

In [4]:
x.shape

torch.Size([12])

In [5]:
len(x)

12

In [6]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros(size=(2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2,3,4),dtype=torch.int32)//5

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32)

In [9]:
torch.randn(2,3,4)

tensor([[[ 0.3515, -0.1185, -1.1081, -0.2519],
         [ 0.0879,  2.0349, -0.2499, -0.4791],
         [-1.8028, -0.5897,  0.6516, -0.2162]],

        [[-0.9496,  0.9785,  0.7982, -0.2807],
         [-0.9365, -0.7632, -0.0890,  1.9943],
         [ 1.4480, -0.1267, -0.4041, -1.3240]]])

In [10]:
a=torch.tensor(list(range(0,30))).reshape(2,3,5)
a[1,2]

tensor([25, 26, 27, 28, 29])

In [11]:
a=torch.tensor(list(range(0,30))).reshape(2,3,5)
b=torch.tensor(list(range(0,70))).reshape(2,7,5)
c=torch.cat((a,b),dim=1)
a,b,c

(tensor([[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14]],
 
         [[15, 16, 17, 18, 19],
          [20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29]]]),
 tensor([[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19],
          [20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34]],
 
         [[35, 36, 37, 38, 39],
          [40, 41, 42, 43, 44],
          [45, 46, 47, 48, 49],
          [50, 51, 52, 53, 54],
          [55, 56, 57, 58, 59],
          [60, 61, 62, 63, 64],
          [65, 66, 67, 68, 69]]]),
 tensor([[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19],
          [20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34]],
 
         [[15, 16, 17, 18

In [12]:
a = torch.arange(1, 11, dtype =torch.float32).reshape((2,5, 1))
b = torch.arange(1, 5)
a, b,a+b

(tensor([[[ 1.],
          [ 2.],
          [ 3.],
          [ 4.],
          [ 5.]],
 
         [[ 6.],
          [ 7.],
          [ 8.],
          [ 9.],
          [10.]]]),
 tensor([1, 2, 3, 4]),
 tensor([[[ 2.,  3.,  4.,  5.],
          [ 3.,  4.,  5.,  6.],
          [ 4.,  5.,  6.,  7.],
          [ 5.,  6.,  7.,  8.],
          [ 6.,  7.,  8.,  9.]],
 
         [[ 7.,  8.,  9., 10.],
          [ 8.,  9., 10., 11.],
          [ 9., 10., 11., 12.],
          [10., 11., 12., 13.],
          [11., 12., 13., 14.]]]))

2.3 Linear Algrebras


In [13]:
torch.tensor(4.5458)*torch.arange(1,4).T

C:\Users\admin\AppData\Local\Temp\ipykernel_3648\2205536390.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4416.)
  torch.tensor(4.5458)*torch.arange(1,4).T


tensor([ 4.5458,  9.0916, 13.6374])

In [14]:
A=torch.arange(1,31,dtype=torch.float32).reshape(2,3,5)

In [15]:
A,A.sum(dim=0,keepdim=True).shape,A.mean(dim=1)

(tensor([[[ 1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10.],
          [11., 12., 13., 14., 15.]],
 
         [[16., 17., 18., 19., 20.],
          [21., 22., 23., 24., 25.],
          [26., 27., 28., 29., 30.]]]),
 torch.Size([1, 3, 5]),
 tensor([[ 6.,  7.,  8.,  9., 10.],
         [21., 22., 23., 24., 25.]]))

2.4 Calculus


In [16]:
import numpy as np

In [17]:
def f(x):
    return 3*x**2-4*x
for h in 10.0**np.arange(-1,-6,-1):
    print(f"{(f(1+h)-f(1))/h:.5f}")

2.30000
2.03000
2.00300
2.00030
2.00003


In [18]:
%matplotlib inline
from matplotlib_inline import backend_inline
def use_svg_display():  #@save
    """Use the svg format to display a plot in Jupyter."""
    backend_inline.set_matplotlib_formats('svg')

2.5 Automatic differentiation


In [19]:
x = torch.arange(4.0, requires_grad=True)

In [20]:
x


tensor([0., 1., 2., 3.], requires_grad=True)

In [21]:
y=2*torch.dot(x,x)

In [22]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [23]:
y

tensor(28., grad_fn=<MulBackward0>)

In [24]:
z=4*torch.dot(x,x)
x.grad.zero_()
z.backward()

In [25]:

x.grad

tensor([ 0.,  8., 16., 24.])

In [26]:
a = torch.randn(size=(2,1), requires_grad=True)

In [27]:
a.grad

In [28]:
a

tensor([[ 1.6093],
        [-0.9439]], requires_grad=True)

In [30]:
import matplotlib.pyplot as plt

# Create x with requires_grad=True
x = torch.linspace(0, 2 * torch.pi, 1000, requires_grad=True)

# Define the function
y = torch.sin(x)

# Reduce y to a scalar to call backward
y.sum().backward()
y.sum()
# x.grad now contains the derivative (dy/dx) for each x
x.grad

tensor([ 1.0000,  1.0000,  0.9999,  0.9998,  0.9997,  0.9995,  0.9993,  0.9990,
         0.9987,  0.9984,  0.9980,  0.9976,  0.9972,  0.9967,  0.9961,  0.9956,
         0.9949,  0.9943,  0.9936,  0.9929,  0.9921,  0.9913,  0.9904,  0.9896,
         0.9886,  0.9877,  0.9867,  0.9856,  0.9845,  0.9834,  0.9823,  0.9811,
         0.9798,  0.9785,  0.9772,  0.9759,  0.9745,  0.9730,  0.9716,  0.9701,
         0.9685,  0.9669,  0.9653,  0.9637,  0.9620,  0.9602,  0.9584,  0.9566,
         0.9548,  0.9529,  0.9510,  0.9490,  0.9470,  0.9450,  0.9429,  0.9408,
         0.9386,  0.9364,  0.9342,  0.9319,  0.9296,  0.9273,  0.9249,  0.9225,
         0.9201,  0.9176,  0.9151,  0.9125,  0.9099,  0.9073,  0.9046,  0.9019,
         0.8992,  0.8964,  0.8936,  0.8908,  0.8879,  0.8850,  0.8821,  0.8791,
         0.8761,  0.8730,  0.8699,  0.8668,  0.8637,  0.8605,  0.8572,  0.8540,
         0.8507,  0.8474,  0.8440,  0.8406,  0.8372,  0.8338,  0.8303,  0.8267,
         0.8232,  0.8196,  0.8160,  0.81

In [31]:
y.sum()

tensor(-7.1041e-06, grad_fn=<SumBackward0>)

In [53]:
t=torch.randint(1,15,size=(1,9),dtype=torch.float32)
t.sum(),t


(tensor(62.), tensor([[ 9., 12., 12.,  6.,  5.,  1.,  9.,  1.,  7.]]))

In [54]:
t.norm()

tensor(23.7065)

In [57]:
b=torch.ones_like(t)*t.sum()/t.numel()
(t-b).norm()**2


tensor(134.8889)

In [60]:
(t-b-0.01).norm()**2

tensor(134.8898)